-- Auto Exported this lua table by Danexx with [Jx3UIAnalytics].

tUIIniStandard = {
	{szIniKey = "._WndType", szLuaName = "WndType"},
	{szIniKey = "._Parent", szLuaName = "Parent"},
	{szIniKey = "._Comment", szLuaName = "Comment"},
	{szIniKey = "Left", szLuaName = "Left"},
	{szIniKey = "Top", szLuaName = "Top"},
	{szIniKey = "Width", szLuaName = "Width"},
	{szIniKey = "Height", szLuaName = "Height"},
	{szIniKey = "$Tip", szLuaName = "Tip"},
	{szIniKey = "TipRichText", szLuaName = "TipRichText"},
	{szIniKey = "OrgTip", szLuaName = "OrgTip"},
	{szIniKey = "ShowTipType", szLuaName = "ShowTipType"},
}

tUIIniMapping = {
	WndFrame = {
		{szIniKey = "DragAreaLeft", szLuaName = "DragAreaLeft"},
		{szIniKey = "DragAreaTop", szLuaName = "DragAreaTop"},
		{szIniKey = "DragAreaWidth", szLuaName = "DragAreaWidth"},
		{szIniKey = "DragAreaHeight", szLuaName = "DragAreaHeight"},
		{szIniKey = "AnimateStartPosX", szLuaName = "AnimateStartPosX"},
		{szIniKey = "AnimateStartPosY", szLuaName = "AnimateStartPosY"},
		{szIniKey = "AnimateEndPosX", szLuaName = "AnimateEndPosX"},
		{szIniKey = "AnimateEndPosY", szLuaName = "AnimateEndPosY"},
		{szIniKey = "AnimateTimeSpace", szLuaName = "AnimateTimeSpace"},
		{szIniKey = "AnimateMoveSpeed", szLuaName = "AnimateMoveSpeed"},
		{szIniKey = "ScriptFile", szLuaName = "ScriptFile"},
		{szIniKey = "IsCustomDragable", szLuaName = "IsCustomDragable"},
		{szIniKey = "DragAreaRight", szLuaName = "DragAreaRight"},
		{szIniKey = "DragAreaBottom", szLuaName = "DragAreaBottom"},
		{szIniKey = "MinWidth", szLuaName = "MinWidth"},
		{szIniKey = "MinHeight", szLuaName = "MinHeight"},
		{szIniKey = "MaxWidth", szLuaName = "MaxWidth"},
		{szIniKey = "MaxHeight", szLuaName = "MaxHeight"},
		{szIniKey = "DisableBringToTop", szLuaName = "DisableBringToTop"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "DisableBreath", szLuaName = "DisableBreath"},
		{szIniKey = "MousePenetrable", szLuaName = "MousePenetrable"},
		{szIniKey = "ItemHandle", szLuaName = "ItemHandle"},
		{szIniKey = "MultiFrame", szLuaName = "MultiFrame"},
		{szIniKey = "ClassName", szLuaName = "ClassName"},
		{szIniKey = "RenderSampling", szLuaName = "RenderSampling"},
		{szIniKey = "BreatheWhenHide", szLuaName = "BreatheWhenHide"},
		{szIniKey = "SelfHoldMouseHover", szLuaName = "SelfHoldMouseHover"},
		{szIniKey = "AreaByEventItem", szLuaName = "AreaByEventItem"},
		{szIniKey = "RenderEvent", szLuaName = "RenderEvent"},
		{szIniKey = "ShowWhenHideUI", szLuaName = "ShowWhenHideUI"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "EnableTabChangeFocus", szLuaName = "EnableTabChangeFocus"},
		{szIniKey = "MouseFollowFocus", szLuaName = "MouseFollowFocus"},
		{szIniKey = "ItemCount", szLuaName = "ItemCount"},
		{szIniKey = "Item_0", szLuaName = "Item_0"},
		{szIniKey = "Item_1", szLuaName = "Item_1"},
		{szIniKey = "Item_2", szLuaName = "Item_2"},
		{szIniKey = "AreaFile", szLuaName = "AreaFile"},
	},
	Handle = {
		{szIniKey = "HandleType", szLuaName = "HandleType"},
		{szIniKey = "FirstItemPosType", szLuaName = "FirstItemPosType"},
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "EventID", szLuaName = "EventID"},
		{szIniKey = "RowSpacing", szLuaName = "RowSpacing"},
		{szIniKey = "PixelScroll", szLuaName = "PixelScroll"},
		{szIniKey = "ControlShow", szLuaName = "ControlShow"},
		{szIniKey = "LockShowAndHide", szLuaName = "LockShowAndHide"},
		{szIniKey = "MousePenetrable", szLuaName = "MousePenetrable"},
		{szIniKey = "IntPos", szLuaName = "IntPos"},
		{szIniKey = "IconImage", szLuaName = "IconImage"},
		{szIniKey = "ExpandIconFrame", szLuaName = "ExpandIconFrame"},
		{szIniKey = "CollapseIconFrame", szLuaName = "CollapseIconFrame"},
		{szIniKey = "IndentWidth", szLuaName = "IndentWidth"},
		{szIniKey = "Indent", szLuaName = "Indent"},
		{szIniKey = "LineColor", szLuaName = "LineColor"},
		{szIniKey = "MinRowHeight", szLuaName = "MinRowHeight"},
		{szIniKey = "AreaFile", szLuaName = "AreaFile"},
	},
	Box = {
		{szIniKey = "Index", szLuaName = "Index"},
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "EventID", szLuaName = "EventID"},
		{szIniKey = "EventName", szLuaName = "EventName"},
		{szIniKey = "LockShowAndHide", szLuaName = "LockShowAndHide"},
	},
	Image = {
		{szIniKey = "Image", szLuaName = "Image"},
		{szIniKey = "Frame", szLuaName = "Frame"},
		{szIniKey = "Alpha", szLuaName = "Alpha"},
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "EventID", szLuaName = "EventID"},
		{szIniKey = "ImageType", szLuaName = "ImageType"},
		{szIniKey = "LockShowAndHide", szLuaName = "LockShowAndHide"},
		{szIniKey = "DisableScale", szLuaName = "DisableScale"},
		{szIniKey = "IntPos", szLuaName = "IntPos"},
	},
	Text = {
		{szIniKey = "RowSpacing", szLuaName = "RowSpacing"},
		{szIniKey = "FontSpacing", szLuaName = "FontSpacing"},
		{szIniKey = "Alpha", szLuaName = "Alpha"},
		{szIniKey = "$Text", szLuaName = "Text"},
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "FontScheme", szLuaName = "FontScheme"},
		{szIniKey = "VAlign", szLuaName = "VAlign"},
		{szIniKey = "HAlign", szLuaName = "HAlign"},
		{szIniKey = "ShowAll", szLuaName = "ShowAll"},
		{szIniKey = "AutoEtc", szLuaName = "AutoEtc"},
		{szIniKey = "MultiLine", szLuaName = "MultiLine"},
		{szIniKey = "EventID", szLuaName = "EventID"},
		{szIniKey = "OrgText", szLuaName = "OrgText"},
		{szIniKey = "LockShowAndHide", szLuaName = "LockShowAndHide"},
		{szIniKey = "MlAutoAdj", szLuaName = "MlAutoAdj"},
		{szIniKey = "CenterEachRow", szLuaName = "CenterEachRow"},
		{szIniKey = "RichText", szLuaName = "RichText"},
		{szIniKey = "DisableScale", szLuaName = "DisableScale"},
		{szIniKey = "Al", szLuaName = "Al"},
	},
	TreeLeaf = {
		{szIniKey = "IconImage", szLuaName = "IconImage"},
		{szIniKey = "ExpandIconFrame", szLuaName = "ExpandIconFrame"},
		{szIniKey = "CollapseIconFrame", szLuaName = "CollapseIconFrame"},
		{szIniKey = "IndentWidth", szLuaName = "IndentWidth"},
		{szIniKey = "Indent", szLuaName = "Indent"},
		{szIniKey = "LineColor", szLuaName = "LineColor"},
		{szIniKey = "HandleType", szLuaName = "HandleType"},
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "IconWidth", szLuaName = "IconWidth"},
		{szIniKey = "IconHeight", szLuaName = "IconHeight"},
		{szIniKey = "ShowLine", szLuaName = "ShowLine"},
		{szIniKey = "EventID", szLuaName = "EventID"},
		{szIniKey = "FirstItemPosType", szLuaName = "FirstItemPosType"},
		{szIniKey = "AlwaysNode", szLuaName = "AlwaysNode"},
	},
	WndPageSet = {
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "Trans", szLuaName = "Trans"},
		{szIniKey = "PageCount", szLuaName = "PageCount"},
		{szIniKey = "Page_0", szLuaName = "Page_0"},
		{szIniKey = "CheckBox_0", szLuaName = "CheckBox_0"},
		{szIniKey = "Page_1", szLuaName = "Page_1"},
		{szIniKey = "CheckBox_1", szLuaName = "CheckBox_1"},
		{szIniKey = "Page_2", szLuaName = "Page_2"},
		{szIniKey = "CheckBox_2", szLuaName = "CheckBox_2"},
		{szIniKey = "Frame", szLuaName = "Frame"},
		{szIniKey = "Page_3", szLuaName = "Page_3"},
		{szIniKey = "CheckBox_3", szLuaName = "CheckBox_3"},
		{szIniKey = "Page_4", szLuaName = "Page_4"},
		{szIniKey = "CheckBox_4", szLuaName = "CheckBox_4"},
		{szIniKey = "Page_5", szLuaName = "Page_5"},
		{szIniKey = "CheckBox_5", szLuaName = "CheckBox_5"},
	},
	WndCheckBox = {
		{szIniKey = "Frame", szLuaName = "Frame"},
		{szIniKey = "UnCheckAndEnable", szLuaName = "UnCheckAndEnable"},
		{szIniKey = "CheckAndEnable", szLuaName = "CheckAndEnable"},
		{szIniKey = "UnCheckAndDisable", szLuaName = "UnCheckAndDisable"},
		{szIniKey = "CheckAndDisable", szLuaName = "CheckAndDisable"},
		{szIniKey = "UnCheckedAndEnableWhenMouseOver", szLuaName = "UnCheckedAndEnableWhenMouseOver"},
		{szIniKey = "CheckedAndEnableWhenMouseOver", szLuaName = "CheckedAndEnableWhenMouseOver"},
		{szIniKey = "CheckedAndDisableWhenMouseOver", szLuaName = "CheckedAndDisableWhenMouseOver"},
		{szIniKey = "UnCheckedAndDisableWhenMouseOver", szLuaName = "UnCheckedAndDisableWhenMouseOver"},
		{szIniKey = "Checking", szLuaName = "Checking"},
		{szIniKey = "UnChecking", szLuaName = "UnChecking"},
		{szIniKey = "Image", szLuaName = "Image"},
		{szIniKey = "RadioButton", szLuaName = "RadioButton"},
		{szIniKey = "UncheckFont", szLuaName = "UncheckFont"},
		{szIniKey = "CheckFont", szLuaName = "CheckFont"},
		{szIniKey = "MouseOverFont", szLuaName = "MouseOverFont"},
		{szIniKey = "MouseDownFont", szLuaName = "MouseDownFont"},
		{szIniKey = "DisableFont", szLuaName = "DisableFont"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "DisableCheck", szLuaName = "DisableCheck"},
		{szIniKey = "CheckedWhenCreate", szLuaName = "CheckedWhenCreate"},
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "Trans", szLuaName = "Trans"},
		{szIniKey = "GrayColor", szLuaName = "GrayColor"},
		{szIniKey = "Up", szLuaName = "Up"},
		{szIniKey = "Down", szLuaName = "Down"},
		{szIniKey = "DisableFrame", szLuaName = "DisableFrame"},
		{szIniKey = "NoOverSound", szLuaName = "NoOverSound"},
		{szIniKey = "Over", szLuaName = "Over"},
		{szIniKey = "OverFrame", szLuaName = "OverFrame"},
		{szIniKey = "CheckOver", szLuaName = "CheckOver"},
		{szIniKey = "SendHoldMsg", szLuaName = "SendHoldMsg"},
		{szIniKey = "NormalGroup", szLuaName = "NormalGroup"},
		{szIniKey = "MouseOverGroup", szLuaName = "MouseOverGroup"},
		{szIniKey = "MouseDownGroup", szLuaName = "MouseDownGroup"},
		{szIniKey = "DisableGroup", szLuaName = "DisableGroup"},
	},
	WndPage = {
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "Frame", szLuaName = "Frame"},
		{szIniKey = "Image", szLuaName = "Image"},
	},
	WndButton = {
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "Trans", szLuaName = "Trans"},
		{szIniKey = "Image", szLuaName = "Image"},
		{szIniKey = "Frame", szLuaName = "Frame"},
		{szIniKey = "GrayColor", szLuaName = "GrayColor"},
		{szIniKey = "Up", szLuaName = "Up"},
		{szIniKey = "Down", szLuaName = "Down"},
		{szIniKey = "DisableFrame", szLuaName = "DisableFrame"},
		{szIniKey = "NoOverSound", szLuaName = "NoOverSound"},
		{szIniKey = "Over", szLuaName = "Over"},
		{szIniKey = "OverFrame", szLuaName = "OverFrame"},
		{szIniKey = "CheckBox", szLuaName = "CheckBox"},
		{szIniKey = "CheckOver", szLuaName = "CheckOver"},
		{szIniKey = "SendHoldMsg", szLuaName = "SendHoldMsg"},
		{szIniKey = "NormalGroup", szLuaName = "NormalGroup"},
		{szIniKey = "MouseOverGroup", szLuaName = "MouseOverGroup"},
		{szIniKey = "MouseDownGroup", szLuaName = "MouseDownGroup"},
		{szIniKey = "DisableGroup", szLuaName = "DisableGroup"},
		{szIniKey = "ButtonDisable", szLuaName = "ButtonDisable"},
		{szIniKey = "NormalFont", szLuaName = "NormalFont"},
		{szIniKey = "MouseOverFont", szLuaName = "MouseOverFont"},
		{szIniKey = "MouseDownFont", szLuaName = "MouseDownFont"},
		{szIniKey = "DisableFont", szLuaName = "DisableFont"},
		{szIniKey = "MousePenetrable", szLuaName = "MousePenetrable"},
		{szIniKey = "DisableBringToTop", szLuaName = "DisableBringToTop"},
	},
	WndNewScrollBar = {
		{szIniKey = "StepCount", szLuaName = "StepCount"},
		{szIniKey = "PageStepCount", szLuaName = "PageStepCount"},
		{szIniKey = "Type", szLuaName = "Type"},
		{szIniKey = "SlideBtn", szLuaName = "SlideBtn"},
		{szIniKey = "AutoHideSlideButton", szLuaName = "AutoHideSlideButton"},
		{szIniKey = "AutoResizeSlideButton", szLuaName = "AutoResizeSlideButton"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "Moveable", szLuaName = "Moveable"},
	},
	WndWindow = {
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "MousePenetrable", szLuaName = "MousePenetrable"},
		{szIniKey = "DragAreaLeft", szLuaName = "DragAreaLeft"},
		{szIniKey = "DragAreaTop", szLuaName = "DragAreaTop"},
		{szIniKey = "DragAreaWidth", szLuaName = "DragAreaWidth"},
		{szIniKey = "DragAreaHeight", szLuaName = "DragAreaHeight"},
		{szIniKey = "AnimateStartPosX", szLuaName = "AnimateStartPosX"},
		{szIniKey = "AnimateStartPosY", szLuaName = "AnimateStartPosY"},
		{szIniKey = "AnimateEndPosX", szLuaName = "AnimateEndPosX"},
		{szIniKey = "AnimateEndPosY", szLuaName = "AnimateEndPosY"},
		{szIniKey = "AnimateTimeSpace", szLuaName = "AnimateTimeSpace"},
		{szIniKey = "AnimateMoveSpeed", szLuaName = "AnimateMoveSpeed"},
		{szIniKey = "MinWidth", szLuaName = "MinWidth"},
		{szIniKey = "MinHeight", szLuaName = "MinHeight"},
		{szIniKey = "MaxWidth", szLuaName = "MaxWidth"},
		{szIniKey = "MaxHeight", szLuaName = "MaxHeight"},
		{szIniKey = "DragAreaRight", szLuaName = "DragAreaRight"},
		{szIniKey = "DragAreaBottom", szLuaName = "DragAreaBottom"},
		{szIniKey = "EnableTabChangeFocus", szLuaName = "EnableTabChangeFocus"},
		{szIniKey = "MouseFollowFocus", szLuaName = "MouseFollowFocus"},
		{szIniKey = "ItemCount", szLuaName = "ItemCount"},
		{szIniKey = "Item_0", szLuaName = "Item_0"},
		{szIniKey = "DisableBreath", szLuaName = "DisableBreath"},
		{szIniKey = "IsCustomDragable", szLuaName = "IsCustomDragable"},
		{szIniKey = "Item_1", szLuaName = "Item_1"},
		{szIniKey = "Item_2", szLuaName = "Item_2"},
		{szIniKey = "ScriptFile", szLuaName = "ScriptFile"},
		{szIniKey = "DisableBringToTop", szLuaName = "DisableBringToTop"},
	},
	WndEdit = {
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "MultiLine", szLuaName = "MultiLine"},
		{szIniKey = "Password", szLuaName = "Password"},
		{szIniKey = "Type", szLuaName = "Type"},
		{szIniKey = "TextLength", szLuaName = "TextLength"},
		{szIniKey = "MaxLen", szLuaName = "MaxLen"},
		{szIniKey = "FontScheme", szLuaName = "FontScheme"},
		{szIniKey = "FocusBgColor", szLuaName = "FocusBgColor"},
		{szIniKey = "FocusBgColorAlpha", szLuaName = "FocusBgColorAlpha"},
		{szIniKey = "SelectBgColorAlpha", szLuaName = "SelectBgColorAlpha"},
		{szIniKey = "RowSpacing", szLuaName = "RowSpacing"},
		{szIniKey = "FontSpacing", szLuaName = "FontSpacing"},
		{szIniKey = "SelFontScheme", szLuaName = "SelFontScheme"},
		{szIniKey = "CaretFontScheme", szLuaName = "CaretFontScheme"},
		{szIniKey = "SelectBgColor", szLuaName = "SelectBgColor"},
		{szIniKey = "Alpha", szLuaName = "Alpha"},
		{szIniKey = "$Text", szLuaName = "Text"},
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "HAlign", szLuaName = "HAlign"},
		{szIniKey = "VAlign", szLuaName = "VAlign"},
	},
	Shadow = {
		{szIniKey = "ShadowColor", szLuaName = "ShadowColor"},
		{szIniKey = "Alpha", szLuaName = "Alpha"},
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "ShadowAlpha", szLuaName = "ShadowAlpha"},
		{szIniKey = "EventID", szLuaName = "EventID"},
		{szIniKey = "LockShowAndHide", szLuaName = "LockShowAndHide"},
	},
	WndScene = {
		{szIniKey = "Frame", szLuaName = "Frame"},
		{szIniKey = "Alpha", szLuaName = "Alpha"},
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "EnableFrameMove", szLuaName = "EnableFrameMove"},
		{szIniKey = "MousePenetrable", szLuaName = "MousePenetrable"},
		{szIniKey = "DisableRenderTerrain", szLuaName = "DisableRenderTerrain"},
		{szIniKey = "DisableRenderSkyBox", szLuaName = "DisableRenderSkyBox"},
		{szIniKey = "EnableAlpha", szLuaName = "EnableAlpha"},
		{szIniKey = "MinWidth", szLuaName = "MinWidth"},
		{szIniKey = "MinHeight", szLuaName = "MinHeight"},
		{szIniKey = "MaxWidth", szLuaName = "MaxWidth"},
		{szIniKey = "MaxHeight", szLuaName = "MaxHeight"},
		{szIniKey = "DragAreaLeft", szLuaName = "DragAreaLeft"},
		{szIniKey = "DragAreaTop", szLuaName = "DragAreaTop"},
		{szIniKey = "DragAreaRight", szLuaName = "DragAreaRight"},
		{szIniKey = "DragAreaBottom", szLuaName = "DragAreaBottom"},
		{szIniKey = "AnimateStartPosX", szLuaName = "AnimateStartPosX"},
		{szIniKey = "AnimateStartPosY", szLuaName = "AnimateStartPosY"},
		{szIniKey = "AnimateEndPosX", szLuaName = "AnimateEndPosX"},
		{szIniKey = "AnimateEndPosY", szLuaName = "AnimateEndPosY"},
		{szIniKey = "AnimateTimeSpace", szLuaName = "AnimateTimeSpace"},
		{szIniKey = "AnimateMoveSpeed", szLuaName = "AnimateMoveSpeed"},
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
	},
	Animate = {
		{szIniKey = "Image", szLuaName = "Image"},
		{szIniKey = "Group", szLuaName = "Group"},
		{szIniKey = "LoopCount", szLuaName = "LoopCount"},
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "LockShowAndHide", szLuaName = "LockShowAndHide"},
		{szIniKey = "EventID", szLuaName = "EventID"},
	},
	Null = {
		{szIniKey = "PosType", szLuaName = "PosType"},
		{szIniKey = "EventID", szLuaName = "EventID"},
	},
	WndWebPage = {
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "$URL", szLuaName = "URL"},
	},
	WndMovie = {
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "Trans", szLuaName = "Trans"},
		{szIniKey = "Image", szLuaName = "Image"},
		{szIniKey = "Frame", szLuaName = "Frame"},
		{szIniKey = "GrayColor", szLuaName = "GrayColor"},
		{szIniKey = "DisableRenderTerrain", szLuaName = "DisableRenderTerrain"},
		{szIniKey = "DisableRenderSkyBox", szLuaName = "DisableRenderSkyBox"},
		{szIniKey = "EnableAlpha", szLuaName = "EnableAlpha"},
	},
	WndMinimap = {
		{szIniKey = "Moveable", szLuaName = "Moveable"},
		{szIniKey = "FollowMove", szLuaName = "FollowMove"},
		{szIniKey = "FollowSize", szLuaName = "FollowSize"},
		{szIniKey = "DummyWnd", szLuaName = "DummyWnd"},
		{szIniKey = "MinimapType", szLuaName = "MinimapType"},
		{szIniKey = "image", szLuaName = "image"},
		{szIniKey = "selfframe", szLuaName = "selfframe"},
		{szIniKey = "defaulttexture", szLuaName = "defaulttexture"},
		{szIniKey = "sharptexture", szLuaName = "sharptexture"},
	},
	Sence = {
		{szIniKey = "PosType", szLuaName = "PosType"},
	},
}
